baseURL = 'https://yinbit.github.io/'
locale = 'en-us'
title = 'yinbitのblog'
theme = "PaperMod"


[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowSearch = true
  SearchEngine = "fuse"

[outputs]
  home = ["HTML", "RSS", "JSON"]  
  
[taxonomies]
  tag = "tags"
  category = "categories"
  
[[menu.main]]
  identifier = "archives"
  name = "archive"
  url = "/archives/"
  weight = 10
[[menu.main]]
  identifier = "search"
  name = "search"
  url = "/search/"
  weight = 40
[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 30
  
[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 100
